import json
import re

with open('frontend/structures.js', 'r') as f:
    data = f.read()

# structures.js looks like:
# const STRUCTURAL_DATA = { ... "pdbs": { "key": "pdb_string..." } };

match = re.search(r'(const STRUCTURAL_DATA = )(\{.*\});?\s*$', data, re.DOTALL)
if not match:
    print("Could not parse structures.js")
    exit(1)

prefix = match.group(1)
json_str = match.group(2)
struct_data = json.loads(json_str)

for key, pdb_string in struct_data.get('pdbs', {}).items():
    lines = pdb_string.split('\n')
    current_res = -1
    chain = 'A'
    out_lines = []
    has_b = False
    
    # First pass: check if it already has chain B
    for line in lines:
        if line.startswith('ATOM') or line.startswith('HETATM'):
            if len(line) > 21 and line[21] == 'B':
                has_b = True
                break
                
    if has_b:
        # Already good
        pass
    else:
        # We need to fix it
        for line in lines:
            if line.startswith('ATOM') or line.startswith('HETATM'):
                try:
                    res_num = int(line[22:26].strip())
                    if current_res != -1 and res_num < current_res - 50:
                        chain = 'B'
                    current_res = res_num
                except ValueError:
                    pass
                
                # Replace chain ID at col 21
                if len(line) > 21:
                    line = line[:21] + chain + line[22:]
                    
            out_lines.append(line)
        
        struct_data['pdbs'][key] = '\n'.join(out_lines)

# Write back
with open('frontend/structures.js', 'w') as f:
    f.write("// structures.js — auto-generated by build_structures_bundle.py\n")
    f.write("// Source: backend/structural/cache/structural_manifest.json + TM-align superposed PDBs\n\n")
    f.write(f"const STRUCTURAL_DATA = {json.dumps(struct_data, indent=2)};\n")

print("Fixed chains in structures.js!")
